#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define TAPPING_FORCE_HOLD

#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          16
#define MOUSEKEY_MOVE_DELTA        1
#define MOUSEKEY_MAX_SPEED         32
#define MOUSEKEY_TIME_TO_MAX       48
#define MOUSEKEY_WHEEL_DELAY       0
#define MOUSEKEY_WHEEL_INTERVAL    64
#define MOUSEKEY_WHEEL_TIME_TO_MAX 64
